config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  resources :hourly_productions, only: [:new, :index] do
    post :bulk_create, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hourly_production.rb
class HourlyProduction < ApplicationRecord
  belongs_to :inverter
  belongs_to :total_daily_production
  validates :production_hour, uniqueness: {scope: :inverter}
end

app/models/inverter.rb
class Inverter < ApplicationRecord
  has_many :hourly_productions
  has_many :total_daily_productions, through: :total_daily_productions_inverters, inverse_of: :inverters
end

app/models/total_daily_production.rb
class TotalDailyProduction < ApplicationRecord
  has_many :hourly_productions
  has_many :inverters, through: :total_daily_productions_inverters, inverse_of: :total_daily_productions

  validates :production_day, presence: true
  validates :production_day, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hourly_productions_controller.rb
class HourlyProductionsController < ApplicationController

  def new
  end

  def bulk_create
    if params[:file].present?
      hourly_data = CsvReader.new(params[:file]).perform
      TotalDailyProductionWriter.new(hourly_data).perform
      HourlyProductionWriter.new(hourly_data).perform
      flash[:alert] = "File succesfully uploaded"
      redirect_to root_path
    else
      flash[:alert] = "You must select a valid CSV file"
      redirect_to new_hourly_production_path
    end

  end

  def index
    @available_days = TotalDailyProduction.all.pluck(:production_day)
    if @selected_day = params[:selected_day]
      @total_daily_production = TotalDailyProduction.find_by(production_day: @selected_day)
      @hourly_productions = @total_daily_production.hourly_productions.includes(:inverter)
    end
  end

  private

  def hourly_productions_params
    params.require(:hourly_production).permit(:file)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hourly_productions_helper.rb
module HourlyProductionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hourly_productions/_form.html.erb
<%= form_with url: bulk_create_hourly_productions_path, method: :post, local: true do |form| %>
  <p>Import a CSV file:</p>
  <%= form.file_field :file, accept: ".csv" %><br>
  <%= form.submit "Import" %>
<% end %>

app/views/hourly_productions/index.html.erb
<h1>Daily statistics</h1>

<%= form_tag(:hourly_productions, method: :get, remote: false) do %>
  <%= select_tag :selected_day, options_for_select(@available_days.unshift("Select a day")), onchange: "this.form.submit();" %>
<% end %>

<% if @selected_day.present? %>
  <h2>Report for <%= @selected_day.to_date.strftime("%d/%m/%y") %></h2><br>
  <h3>Total energy produced: <%= @total_daily_production.energy %></h3>
  <table>
    <tr>
      <td>ID</td>
      <td>Time</td>
      <td>Energy</td>
    </tr>
    <% @hourly_productions.each do |hp| %>
    <tr>
      <td><%= hp.inverter.id %></td>
      <td><%= hp.production_hour.strftime("%Hh") %></td>
      <td><%= hp.energy %></td>
    </tr>
    <% end %>
  </table>

<% end %>
<%= link_to 'Retour', root_path %>

app/views/hourly_productions/new.html.erb
<h1>Import CSV</h1>

<%= render 'form' %>
<%= link_to 'Retour', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datalogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Datalogger</h1>
<ul>
  <li><%= link_to "Import a new CSV", new_hourly_production_path %></li>
  <li><%= link_to "Get daily statistics", hourly_productions_path %></li>
</ul>

app/views/partials/_flash_messages.html.erb
<%= flash[:alert] || nil %>